name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-2019, vs: "Visual Studio 2019" } # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019
        - { os: windows-2022, vs: "Visual Studio 2022" } # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022

    name: "${{matrix.config.vs}}"
    steps:
    - name: Install WPT
      shell: powershell
      if: ${{ matrix.config.os ==  'windows-2022' }}
      run: |
        wget https://go.microsoft.com/fwlink/?linkid=2196127 -out adksetup.exe
        .\adksetup.exe /quiet /norestart /features OptionId.WindowsPerformanceToolkit
        wget https://gist.githubusercontent.com/Trass3r/ab7cbe5686323ae63a67a32915d5edfc/raw/59993931ccfb366e3c065dc7d2fd202631256e89/test.wpaProfile -out test.wpaProfile
    - uses: actions/checkout@v3

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build x64
      shell: bash
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake .. -A x64

        vcperf -start -level3 MyVCSession
        cmake --build . --config Release
        vcperf -stop -templates MyVCSession build.etl
        #wpa -version
        wpaexporter build.etl -profile ../test.wpaProfile -delimiter "\t"
        cat *.csv

        ctest --output-on-failure -C Release
        cmake --build . --config Debug
        ctest --output-on-failure -C Debug
